[package]
name = "soundflow"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
rand = "0.8"
df = { git = "https://github.com/Rikorose/DeepFilterNet", package = "df" }
log = "0.4"
env_logger = "0.10"
hound = "3.4"
